
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // package.json#prisma.seed is deprecated in this Prisma version and gets
    // overridden by this file, so the seed command has to live here too.
    // `-r tsconfig-paths/register` added in Sprint 4 — seed.ts now imports
    // src/lib/stage-progress.ts, which (like every other src/lib file) uses
    // the `@/*` tsconfig path alias; ts-node doesn't apply tsconfig `paths`
    // on its own, so without this the alias resolves fine everywhere the
    // app actually runs (Next's bundler understands it) but fails here.
    seed: "ts-node -r tsconfig-paths/register --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // Pooled (PgBouncer, port 6543) for normal app queries; migrations need
    // the unpooled port 5432 connection below to run DDL/shadow-db operations,
    // which PgBouncer's transaction mode doesn't support.
    url: env("DATABASE_URL"),
    directUrl: env("DIRECT_URL"),
  },
});
