
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // package.json#prisma.seed is deprecated in this Prisma version and gets
    // overridden by this file, so the seed command has to live here too.
    seed: "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // Pooled (PgBouncer, port 6543) for normal app queries; migrations need
    // the unpooled port 5432 connection below to run DDL/shadow-db operations,
    // which PgBouncer's transaction mode doesn't support.
    url: env("DATABASE_URL"),
    directUrl: env("DIRECT_URL"),
  },
});
